import Link from 'next/link'

export default function LandingPage() {
  return (
    <main className="min-h-screen bg-white">
      {/* Navigation */}
      <nav className="border-b border-gray-100 px-4 py-4">
        <div className="max-w-5xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="text-xl font-bold text-primary">StudySync</span>
          </div>
          <div className="flex items-center gap-3">
            <Link
              href="/login"
              className="text-sm font-medium text-gray-600 hover:text-gray-900 transition-colors"
            >
              Sign In
            </Link>
            <Link
              href="/register"
              className="btn-primary text-sm"
            >
              Get Started
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="px-4 py-20 text-center">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-4xl sm:text-5xl font-bold text-gray-900 leading-tight">
            Study Smarter with{' '}
            <span className="text-primary">AI-Powered</span>{' '}
            Collaboration
          </h1>
          <p className="mt-6 text-lg text-gray-500 leading-relaxed max-w-2xl mx-auto">
            StudySync helps students organize study schedules, track progress,
            collaborate with peers, and receive personalized AI study plans.
          </p>
          <div className="mt-8 flex flex-col sm:flex-row gap-3 justify-center">
            <Link
              href="/register"
              className="btn-primary text-base px-8 py-3"
            >
              Get Started for Free
            </Link>
            <Link
              href="/login"
              className="inline-flex items-center justify-center px-8 py-3 rounded-lg border border-gray-200 text-base font-medium text-gray-700 hover:bg-gray-50 transition-colors"
            >
              Sign In
            </Link>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="px-4 py-16 bg-gray-50">
        <div className="max-w-5xl mx-auto">
          <h2 className="text-2xl font-bold text-gray-900 text-center mb-12">
            Everything you need to excel
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature) => (
              <div
                key={feature.title}
                className="bg-white rounded-xl p-6 border border-gray-100 shadow-sm"
              >
                <div className="w-10 h-10 bg-primary/10 rounded-lg flex items-center justify-center mb-4">
                  <span className="text-xl" aria-hidden="true">
                    {feature.icon}
                  </span>
                </div>
                <h3 className="font-semibold text-gray-900 mb-2">{feature.title}</h3>
                <p className="text-sm text-gray-500 leading-relaxed">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="px-4 py-20 text-center">
        <div className="max-w-xl mx-auto">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">
            Ready to level up your studies?
          </h2>
          <p className="text-gray-500 mb-8">
            Join thousands of students already using StudySync to reach their academic goals.
          </p>
          <Link href="/register" className="btn-primary text-base px-8 py-3">
            Create Free Account
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-gray-100 px-4 py-8 text-center">
        <p className="text-sm text-gray-400">
          © {new Date().getFullYear()} StudySync. All rights reserved.
        </p>
      </footer>
    </main>
  )
}

const features = [
  {
    icon: '📚',
    title: 'Study Session Tracking',
    description:
      'Create structured study sessions, track time, and log completed work to see your progress over time.',
  },
  {
    icon: '🤝',
    title: 'Peer Collaboration',
    description:
      'Follow fellow students, view their study activity, and stay motivated through shared accountability.',
  },
  {
    icon: '🤖',
    title: 'AI Study Plans',
    description:
      'Get personalized weekly study plans generated by AI based on your subjects, goals, and available time.',
  },
  {
    icon: '📊',
    title: 'Progress Analytics',
    description:
      'Visualize your study hours, task completion, and subject distribution with intuitive charts.',
  },
  {
    icon: '🎯',
    title: 'Task Management',
    description:
      'Organize your study tasks by subject from a curated library, keeping everything focused.',
  },
  {
    icon: '💡',
    title: 'AI Study Tips',
    description:
      'Receive subject-specific learning tips and strategies powered by AI to optimize your study techniques.',
  },
]
